name: saltstack-tinc-formula
source: https://github.com/bechtoldt/saltstack-tinc-formula
summary: SaltStack Formula to set up and configure tinc, a Virtual Private Network (VPN) daemon
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
  - configure tinc
  - fetch node data
